spring:
  config:
    import:
      - 'optional:configtree:/run/secrets/'
      - 'optional:configtree:/run/configs/'
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:terab}
    password: ${RABBITMQ_PASSWORD:}
  cloud:
    function:
      definition: processPushChallenge
    stream:
      bindings:
        processPushChallenge-in-0:
          destination: terab.events
          group: notification-push
          content-type: application/json
      rabbit:
        bindings:
          processPushChallenge-in-0:
            consumer:
              binding-routing-key: auth.2fa.challenge
              exchange-type: topic

server:
  port: 8082

firebase:
  credentials-path: ${FIREBASE_CREDENTIALS_PATH:}

management:
  endpoints:
    web:
      exposure:
        include: health
